### ISSUE TITLE
pth2onnx

### ISSUE THREAD

**Issue by aclicewuyu** [mikwieczorek/centroids-reid#22]
could you give a pth2onnx ? i can’t onvert model to onnx maybe because of no 'forward' there

**Comment by joynjo** [comment]
@aclicewuyu @mikwieczorek have you found any solution for this issue?

**Comment by mikwieczorek** [comment]
Sorry, didn't look into it yet. 
It is on my 'to-do' list definitely and I will fix it along with other changes

**Comment by aclicewuyu** [comment]
I have solved this problem, thank you

**Comment by YuzhouPeng** [comment]
> I have solved this problem, thank you

Have you solved this issue? I got error when I convert model

(centroidreid) pengyuzhou@h3c-UniServer-R5300-G31:/opt/DataDisk2/pyz/workspace/centroids-reid$ python inference/create_embeddings.py --config_file=configs/320_resnet50_ibn_a.yml GPU_IDS [0] DATASETS.ROOT_DIR '/opt/DataDisk2/pyz/workspace/centroids-reid/test/' TEST.IMS_PER_BATCH 128 OUTPUT_DIR '/opt/DataDisk2/pyz/workspace/centroids-reid/outputs/' TEST.ONLY_TEST True MODEL.PRETRAIN_PATH "/opt/DataDisk2/pyz/workspace/centroids-reid/logs/dukemtmcreid/256_resnet50/train_ctl_model/version_25/auto_checkpoints/checkpoint_119.pth"
INFO:__main__:Preparing data using <class 'inference_utils.ImageDataset'> dataset class
/opt/DataDisk2/pyz/workspace/centroids-reid/test/ 1
['/opt/DataDisk2/pyz/workspace/centroids-reid/test/0_c006_c1210798.jpg']
Loading pretrained ImageNet model......
Traceback (most recent call last):
  File "inference/create_embeddings.py", line 86, in <module>
    torch.onnx.export(model,dummy_input,"centroid_reid_ctl_onnx.onnx",input_names = [input_name],output_names = [output_name], dynamic_axes={'input': {0: 'batch'}, 'output': {0: 'batch'}} ,opset_version=13)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 459, in _model_to_graph
    _retain_param_name)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 447, in forward
    return super().forward(*args, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _forward_unimplemented
    raise NotImplementedError
NotImplementedError

**Comment by YuzhouPeng** [comment]
@aclicewuyu hello I tried to_onnx function in pytorch lightning， but still got notimplemented error, can you possibly give me some hints?

**Comment by aclicewuyu** [comment]
> 

yes，i will send the to_onnx to you through the email

**Comment by aclicewuyu** [comment]
@YuzhouPeng you can have a try
import [argparse](https://docs.python.org/3/library/argparse.html)
from [config](https://pypi.org/project/config) import cfg
from train_ctl_model import CTLModel
import https://github.com/pytorch/pytorch
import torch.onnx

def main(args):    
    model = CTLModel  
    model = model.load_from_checkpoint(
        args.input_file
    )
    input_sample=torch.randn((args.batch_size,3,256,128)) 
    model.eval()
    model.forward=model.test_step
    dynamic_axes = {'image': {0: '-1'}, 'class': {0: '-1'}} 
    torch.onnx.export(model, input_sample, args.output_file, export_params=True,\
    input_names = ['input'], output_names = ['output'], dynamic_axes = dynamic_axes,opset_version=11, verbose=True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Model to ONNX")
    parser.add_argument("--output_file", default="centroid-reid_r50_bs1.onnx", help="name of onnx", type=str)
    parser.add_argument("--input_file", default="./models/dukemtmcreid_resnet50_256_128_epoch_120.ckpt", type=str)
    parser.add_argument("--batch_size", default=1, help="batch_size", type=int)
    args = parser.parse_args()
    main(args)

**Comment by aclicewuyu** [comment]
yes，i have found a solution.thank you 

发自我的iPhone

**Comment by joseph-cv** [comment]
Hello @aclicewuyu, thank you for sharing your solution. However, when I tried to run it, I encountered the following error. Can you guess what it's wrong? 

Loading pretrained ImageNet model......
/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/onnx/utils.py:1109: UserWarning: Provided key image for dynamic axes is not a valid input/output name
  warnings.warn("Provided key {} for dynamic axes is not a valid input/output name".format(key))
/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/onnx/utils.py:1109: UserWarning: Provided key class for dynamic axes is not a valid input/output name
  warnings.warn("Provided key {} for dynamic axes is not a valid input/output name".format(key))
Traceback (most recent call last):
  File "export_to_onnx.py", line 31, in <module>
    main(args)
  File "export_to_onnx.py", line 15, in main
    torch.onnx.export(model,
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/onnx/__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/onnx/utils.py", line 632, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/onnx/utils.py", line 409, in _model_to_graph
    graph, params, torch_out = _create_jit_graph(model, args,
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/onnx/utils.py", line 379, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/onnx/utils.py", line 342, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/jit/_trace.py", line 1148, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/jit/_trace.py", line 125, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/me/anaconda3/envs/centroidsREID/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 39, in wrapped_fn
    return fn(*args, **kwargs)
TypeError: test_step() missing 1 required positional argument: 'batch_idx'

@mikwieczorek
