### ISSUE TITLE
NotImplement Error when converting pth to onnx

### ISSUE THREAD

**Issue by YuzhouPeng** [mikwieczorek/centroids-reid#25]
Hello, I trained a pth and try to convert model to onnx during inference session,

but I got following error:

(centroidreid) pengyuzhou@h3c-UniServer-R5300-G31:/opt/DataDisk2/pyz/workspace/centroids-reid$ python inference/create_embeddings.py --config_file=configs/320_resnet50_ibn_a.yml GPU_IDS [0] DATASETS.ROOT_DIR '/opt/DataDisk2/pyz/workspace/centroids-reid/test/' TEST.IMS_PER_BATCH 128 OUTPUT_DIR '/opt/DataDisk2/pyz/workspace/centroids-reid/outputs/' TEST.ONLY_TEST True MODEL.PRETRAIN_PATH "/opt/DataDisk2/pyz/workspace/centroids-reid/logs/dukemtmcreid/256_resnet50/train_ctl_model/version_25/auto_checkpoints/checkpoint_119.pth"
INFO:__main__:Preparing data using <class 'inference_utils.ImageDataset'> dataset class
/opt/DataDisk2/pyz/workspace/centroids-reid/test/ 1
['/opt/DataDisk2/pyz/workspace/centroids-reid/test/0_c006_c1210798.jpg']
Loading pretrained ImageNet model......
Traceback (most recent call last):
  File "inference/create_embeddings.py", line 86, in <module>
    torch.onnx.export(model,dummy_input,"centroid_reid_ctl_onnx.onnx",input_names = [input_name],output_names = [output_name], dynamic_axes={'input': {0: 'batch'}, 'output': {0: 'batch'}} ,opset_version=13)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 459, in _model_to_graph
    _retain_param_name)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 447, in forward
    return super().forward(*args, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 201, in _forward_unimplemented
    raise NotImplementedError
NotImplementedError

How can I solve this issue? Thank u

**Comment by aclicewuyu** [comment]
have a try 
  model = CTLModel  
    model = model.load_from_checkpoint(
        "./models/dukemtmcreid_resnet50_256_128_epoch_120.ckpt"
    )
    input_sample=torch.randn((1,3,256,128)) 
    model.eval()
    model.forward=model.test_step
    dynamic_axes = {'image': {0: '-1'}, 'class': {0: '-1'}} 
    torch.onnx.export(model, input_sample, args.output_file, export_params=True, input_names = ['input'], output_names = ['output'], dynamic_axes = dynamic_axes,opset_version=11, verbose=True)

**Comment by YuzhouPeng** [comment]
> have a try model = CTLModel model = model.load_from_checkpoint( "./models/dukemtmcreid_resnet50_256_128_epoch_120.ckpt" ) input_sample=torch.randn((1,3,256,128)) model.eval() model.forward=model.test_step dynamic_axes = {'image': {0: '-1'}, 'class': {0: '-1'}} torch.onnx.export(model, input_sample, args.output_file, export_params=True, input_names = ['input'], output_names = ['output'], dynamic_axes = dynamic_axes,opset_version=11, verbose=True)

I tried:

    input_sample=torch.randn((1,3,320,320))

    model.eval()
    model.forward=model.test_step
    dynamic_axes = {'image': {0: '-1'}, 'class': {0: '-1'}}
    torch.onnx.export(model, input_sample, "centroidreid_onnx.onnx", export_params=True,
    input_names = ['input'], output_names = ['output'], dynamic_axes = dynamic_axes,opset_version=11, verbose=True)

but got following error:

/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py:1189: UserWarning: Provided key image for dynamic axes is not a valid input/output name
  warnings.warn("Provided key {} for dynamic axes is not a valid input/output name".format(key))
/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py:1189: UserWarning: Provided key class for dynamic axes is not a valid input/output name
  warnings.warn("Provided key {} for dynamic axes is not a valid input/output name".format(key))
Traceback (most recent call last):
  File "inference/create_embeddings.py", line 128, in <module>
    input_names = ['input'], output_names = ['output'], dynamic_axes = dynamic_axes,opset_version=11, verbose=True)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 459, in _model_to_graph
    _retain_param_name)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 39, in wrapped_fn
    return fn(*args, **kwargs)
TypeError: test_step() missing 1 required positional argument: 'batch_idx'

how can I fix it? thanks

**Comment by aclicewuyu** [comment]
in bases.py
@rank_zero_only
    def test_step(self, batch, batch_idx=1):
        ret = self.validation_step(batch, batch_idx)
        return ret

**Comment by YuzhouPeng** [comment]
(centroidreid) pengyuzhou@h3c-UniServer-R5300-G31:/opt/DataDisk2/pyz/workspace/centroids-reid$ python inference/create_embeddings.py --config_file="configs/320_resnet50_ibn_a.yml"  GPU_IDS [3] DATASETS.ROOT_DIR 'test' TEST.IMS_PER_BATCH 128 OUTPUT_DIR 'outputs' TEST.ONLY_TEST True MODEL.PRETRAIN_PATH "/opt/DataDisk2/pyz/workspace/centroids-reid/logs/dukemtmcreid/256_resnet50/train_ctl_model/version_25/auto_checkpoints/checkpoint_119.pth"
INFO:__main__:Preparing data using <class 'inference_utils.ImageDataset'> dataset class
test 3
['test/0_c006_c1210798 copy 2.jpg', 'test/0_c006_c1210798 copy.jpg', 'test/0_c006_c1210798.jpg']
<torch.utils.data.dataloader.DataLoader object at 0x7fa46dc46750>
Loading pretrained ImageNet model......
load model success
load models
/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py:1189: UserWarning: Provided key image for dynamic axes is not a valid input/output name
  warnings.warn("Provided key {} for dynamic axes is not a valid input/output name".format(key))
/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py:1189: UserWarning: Provided key class for dynamic axes is not a valid input/output name
  warnings.warn("Provided key {} for dynamic axes is not a valid input/output name".format(key))
./modelling/bases.py:173: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  x, class_labels, camid, idx = batch
Traceback (most recent call last):
  File "inference/create_embeddings.py", line 128, in <module>
    input_names = ['input'], output_names = ['output'], dynamic_axes = dynamic_axes,opset_version=11, verbose=True)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 459, in _model_to_graph
    _retain_param_name)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 39, in wrapped_fn
    return fn(*args, **kwargs)
  File "./modelling/bases.py", line 388, in test_step
    ret = self.validation_step(batch, batch_idx)
  File "/home/pengyuzhou/miniconda3/envs/centroidreid/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py", line 39, in wrapped_fn
    return fn(*args, **kwargs)
  File "./modelling/bases.py", line 173, in validation_step
    x, class_labels, camid, idx = batch
ValueError: not enough values to unpack (expected 4, got 1)

**Comment by YuzhouPeng** [comment]
problem solved, thank you so much.

**Comment by 22ema** [comment]
Hello.
@YuzhouPeng How can you solve a problem. could you help me please.

**Comment by masa8** [comment]
Thank you, @aclicewuyu for useful code snippet. 
Your code saved me a lot of time!
and then,, I have one question.

What is the intention behind this?
> model.forward=model.test_step

Obviously, I think, the line of code is for avoiding `NotImplementedError` though,
It is not common practice to directly set `model.forward` equal to `model.test_step`.
`model.forward` defines forward as the main computation performed by the model and `model.test_step` defines  a custom method within training or testing loop. 

Maybe I should read more code. If I did, I'm sure I'd understand why.

**Comment by masa8** [comment]
Hi @22ema ,
You may have already done this, but...
I could export onnx model by modifying like this:
I don't know if it's good way or not for now though.

```python
def validation_step(self, batch, batch_idx):
        self.backbone.eval()
        self.bn.eval()
        # x, class_labels, camid, idx = batch  
        # dummy added
        x, class_labels, camid, idx = batch, torch.tensor((0)),torch.tensor((0)),torch.tensor((0))  
        with torch.no_grad():
            _, emb = self.backbone(x)
            emb = self.bn(emb)
        return {"emb": emb, "labels": class_labels, "camid": camid, "idx": idx}
```    
In validation phase, Validation dataset, it's actually a subclass of `BaseDatasetLabelled`, returns a tuple of (sample, target, camid, idx) and DataLoader combines these tuples into batches of the form ((sample1, sample2, ...), (target1, target2, ...), (camid1,camid2,...),(idx1,idx2,...)) and then  PyTorch-lighting generate `forward()` to call validation_step() automatically and give `batch` to the method. 

On the other hand,  `torch.onnx.export` doesn't generate `forward` method and `forward`  is needed to export onnx model. 
so, when `forward` is called, `model.forward=model.test_step` changes it to use `test_step` and torch.onnx.export doesn't create `class_labels`, `camid`, `idx`. So dummy was made for them.
